# Generated by Django 3.0.2 on 2020-01-10 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Profile'),
        ),
    ]
